#!/usr/bin/env bash

make

#Xephyr +extension RANDR +xinerama -screen 960x460+0+310 -screen 960x460+960+310 -ac :1 &
Xephyr -screen 1600x900+2080+90 -ac :1 &

sleep 0.1

DISPLAY=:1 ./YATwm -nc config

pkill Xephyr
